baseURL = "https://axill86.github.io/aws-csa-associate/"
languageCode = "en-us"
title = "AWS Certified Solutions Architect – Associate"
theme = "book"
publishDir = "docs"
[params]
    BookMenuBundle = "/menu"